export type PatientStatus = "activo" | "en_tratamiento" | "seguimiento" | "alta"

export interface Patient {
  id: number
  nombre: string
  apellido: string
  dni: string
  email: string
  diagnostico: string
  estado: PatientStatus
  voluntarioAsignado: string | null
  ultimaVisita: string
  fechaRegistro: string
}

export const patients: Patient[] = [
  {
    id: 1,
    nombre: "María",
    apellido: "Torres Quispe",
    dni: "43821056",
    email: "m.torres@gmail.com",
    diagnostico: "Cáncer de mama",
    estado: "en_tratamiento",
    voluntarioAsignado: "Ana Villanueva",
    ultimaVisita: "2026-03-17T10:30:00",
    fechaRegistro: "2025-11-03",
  },
  {
    id: 2,
    nombre: "José",
    apellido: "Quispe Mamani",
    dni: "28374651",
    email: "jose.quispe@hotmail.com",
    diagnostico: "Cáncer de próstata",
    estado: "activo",
    voluntarioAsignado: "Carlos Mendoza",
    ultimaVisita: "2026-03-15T09:00:00",
    fechaRegistro: "2025-09-15",
  },
  {
    id: 3,
    nombre: "Rosa",
    apellido: "Díaz Flores",
    dni: "31928475",
    email: "rosa.diaz@gmail.com",
    diagnostico: "Cáncer de cuello uterino",
    estado: "seguimiento",
    voluntarioAsignado: null,
    ultimaVisita: "2026-03-10T11:00:00",
    fechaRegistro: "2025-06-22",
  },
  {
    id: 4,
    nombre: "Carlos",
    apellido: "Salinas Ramos",
    dni: "47382910",
    email: "c.salinas@gmail.com",
    diagnostico: "Cáncer de pulmón",
    estado: "en_tratamiento",
    voluntarioAsignado: "Ana Villanueva",
    ultimaVisita: "2026-03-18T08:30:00",
    fechaRegistro: "2026-01-08",
  },
  {
    id: 5,
    nombre: "Elena",
    apellido: "Mendoza García",
    dni: "29485736",
    email: "elena.m@outlook.com",
    diagnostico: "Cáncer de mama",
    estado: "alta",
    voluntarioAsignado: "Luis Paredes",
    ultimaVisita: "2026-02-28T14:00:00",
    fechaRegistro: "2025-03-14",
  },
  {
    id: 6,
    nombre: "Pedro",
    apellido: "Vargas Huamán",
    dni: "35627184",
    email: "pedro.v@gmail.com",
    diagnostico: "Cáncer de colon",
    estado: "activo",
    voluntarioAsignado: "Carlos Mendoza",
    ultimaVisita: "2026-03-16T16:00:00",
    fechaRegistro: "2025-12-01",
  },
  {
    id: 7,
    nombre: "Carmen",
    apellido: "Flores Cárdenas",
    dni: "41736289",
    email: "carmen.flores@gmail.com",
    diagnostico: "Cáncer de mama",
    estado: "en_tratamiento",
    voluntarioAsignado: null,
    ultimaVisita: "2026-03-12T10:00:00",
    fechaRegistro: "2026-01-20",
  },
  {
    id: 8,
    nombre: "Roberto",
    apellido: "Lima Castillo",
    dni: "26493817",
    email: "r.lima@hotmail.com",
    diagnostico: "Cáncer de próstata",
    estado: "seguimiento",
    voluntarioAsignado: "Luis Paredes",
    ultimaVisita: "2026-03-05T09:30:00",
    fechaRegistro: "2025-07-30",
  },
  {
    id: 9,
    nombre: "Isabel",
    apellido: "Soto Tapia",
    dni: "38201947",
    email: "isabel.soto@gmail.com",
    diagnostico: "Cáncer de cuello uterino",
    estado: "activo",
    voluntarioAsignado: "Ana Villanueva",
    ultimaVisita: "2026-03-17T15:30:00",
    fechaRegistro: "2025-10-11",
  },
  {
    id: 10,
    nombre: "Alejandro",
    apellido: "Ruiz Peralta",
    dni: "44018273",
    email: "a.ruiz@gmail.com",
    diagnostico: "Cáncer de pulmón",
    estado: "en_tratamiento",
    voluntarioAsignado: "Carlos Mendoza",
    ultimaVisita: "2026-03-14T11:00:00",
    fechaRegistro: "2025-08-25",
  },
  {
    id: 11,
    nombre: "Lucía",
    apellido: "Paredes Vega",
    dni: "33748201",
    email: "lucia.p@outlook.com",
    diagnostico: "Cáncer de mama",
    estado: "alta",
    voluntarioAsignado: null,
    ultimaVisita: "2026-02-20T13:00:00",
    fechaRegistro: "2024-11-05",
  },
  {
    id: 12,
    nombre: "Fernando",
    apellido: "Castro Núñez",
    dni: "27384910",
    email: "f.castro@gmail.com",
    diagnostico: "Cáncer de colon",
    estado: "activo",
    voluntarioAsignado: "Luis Paredes",
    ultimaVisita: "2026-03-13T10:00:00",
    fechaRegistro: "2025-05-18",
  },
]

export const statusLabels: Record<PatientStatus, string> = {
  activo: "Activo",
  en_tratamiento: "En tratamiento",
  seguimiento: "Seguimiento",
  alta: "Alta médica",
}
